### ISSUE TITLE
TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by neurotensin** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#33]
Hi,

I installed all the requirements (pip -r requirements.txt) , using python3 (tried 3.5 and 3.6). 
This is debian buster, but I have tried many dockers.

> 

Using TensorFlow backend.
[Model] Model Compiled
Time taken: 0:00:00.955068
Traceback (most recent call last):
  File "run.py", line 84, in <module>
    main()
  File "run.py", line 46, in main
    normalise = configs['data']['normalise']
  File "/tmp/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 44, in get_train_data
    x, y = self._next_window(i, seq_len, normalise)
  File "/tmp/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 68, in _next_window
    window = self.normalise_windows(window, single_window=True)[0] if normalise else window
  File "/tmp/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 78, in normalise_windows
    normalised_window = [((float(p) / float(window[0])) - 1) for p in window]
  File "/tmp/FinanceModels/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 78, in <listcomp>
    normalised_window = [((float(p) / float(window[0])) - 1) for p in window]
TypeError: only size-1 arrays can be converted to Python scalars

> 

Anyone out there get the standard example to work?

NT.

**Comment by neurotensin** [comment]
Trying the sinewave example, it goes as far as:

ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (16, 1)

the call stack:

File "run.py", line 84, in <module>
    main()
  File "run.py", line 68, in main
    steps_per_epoch = steps_per_epoch
  File "tmp/LSTM-Neural-Network-for-Time-Series-Prediction/core/model.py", line 83, in train_generator
    workers=1
  File "tmp/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "tmp/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "tmp/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "tmp/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "tmp/.local/lib/python3.6/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "tmp/.local/lib/python3.6/site-packages/keras/engine/training_utils.py", line 127, in standardize_input_data
    'with shape ' + str(data_shape))

**Comment by neurotensin** [comment]
The sinewave works using the internal memory model. Something clearly unstable between code pieces, I'll try track it down.
