### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by sandeepgajjam** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#44]
Using TensorFlow backend.
[Model] Model Compiled
Time taken: 0:00:00.847986
Traceback (most recent call last):
  File "run.py", line 91, in <module>
    main()
  File "run.py", line 50, in main
    normalise=configs['data']['normalise']
  File "/home/ubuntu/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 44, in get_train_data
    x, y = self._next_window(i, seq_len, normalise)
  File "/home/ubuntu/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 69, in _next_window
    window = self.normalise_windows(window, single_window=True)[0] if normalise else window
  File "/home/ubuntu/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 81, in normalise_windows
    normalised_col = [((float(p) / float(window[0, col_i])) - 1) for p in window[:, col_i]]
  File "/home/ubuntu/LSTM-Neural-Network-for-Time-Series-Prediction/core/data_processor.py", line 81, in <listcomp>
    normalised_col = [((float(p) / float(window[0, col_i])) - 1) for p in window[:, col_i]]
ZeroDivisionError: float division by zero

Can you fix this please

**Comment by fgadaleta** [comment]
Fixed in https://github.com/fgadaleta/LSTM-Neural-Network-for-Time-Series-Prediction/commit/3d3c3a3ff2c4df349d54d1d7d9739cab2a522e16

**Comment by sandeepgajjam** [comment]
Using TensorFlow backend.
[Model] Model Compiled
Time taken: 0:00:00.582537
[Model] Training Started
[Model] 2 epochs, 32 batch size, 124 batches per epoch
Epoch 1/2
Traceback (most recent call last):
  File "run.py", line 91, in <module>
    main()
  File "run.py", line 74, in main
    save_dir=configs['model']['save_dir']
  File "/home/ubuntu/LSTM-Neural-Network-for-Time-Series-Prediction/core/model.py", line 83, in train_generator
    workers=1
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected lstm_1_input to have shape (49, 2) but got array with shape (50, 2)

**Comment by fgadaleta** [comment]
Change the input in the config, from 49 to 50
