### ISSUE TITLE
TypeError: Expected int32, got <tensorflow.python.ops.variables.Variable object at 0x7f3d6a773a10> of type 'Variable' instead.

### ISSUE THREAD

**Issue by cuiyi129** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#5]
When I run the code,I meet the following problems:
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    model = lstm.build_model([1, 50, 100, 1])
  File "/home/cuiyi/Downloads/SPARNN-release/data/LSTM/LSTM-Neural-Network-for-Time-Series-Prediction/lstm.py", line 51, in build_model
    return_sequences=True))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 276, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 370, in create_input_layer
    self(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 710, in build
    self.W = K.concatenate([self.W_i, self.W_f, self.W_c, self.W_o])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 716, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got <tensorflow.python.ops.variables.Variable object at 0x7f3d6a773a10> of type 'Variable' instead.

**Comment by jaungiers** [comment]
Code has been updated to support codebase Python 3.5 rather than 2.7 now... Please try it with the new codebase, making sure you have the correct versions of libraries installed as per the ReadMe file.

**Comment by cuiyi129** [comment]
I'm sorry,I'm a beginner.But I want to ask ....Can you provide the code for python 2.7 for reference?Thank you very much.

**Comment by jaungiers** [comment]
The 2.7 code should be easy enough to derive yourself. Change the print statements and take out decode() from str.decode().split() and I think that's it... If you just run the code I have with 2.7 and then work your way through the errors one by one you'll convert from 3.5 to 2.7. That's how I did it and it when converting from 2.7 to 3.5 took me 5mins.
