### ISSUE TITLE
TypeError when running

### ISSUE THREAD

**Issue by BasharAG** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#7]
I tried running the code and installing dependencies using pip and pip3 and I tried running the code using python and python3, but I keep getting this:

```
Using TensorFlow backend.
> Loading data...
> Data Loaded. Compiling...
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    model = lstm.build_model([1, 50, 100, 1])
  File "/root/LSTM/lstm.py", line 53, in build_model
    return_sequences=True))
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 931, in __init__
    super(LSTM, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 181, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 275, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_dim')
```

**Comment by pusj** [comment]
Hello Bashar,

 It seems as if you are using Python 2.7, this code is written to be used with Python 3.5.

BR
Staffan

**Comment by BasharAG** [comment]
Thanks for responding. I used the python3 command to run it, but got the same error.

**Comment by jaungiers** [comment]
Steffan does seem to be right from what I can see, despite you using pip3 it is using a python 2.7 runtime... if you type "python --version" into your console what do you get? If you get anything other than 3.5.x+ then that's your problem.

**Comment by BasharAG** [comment]
My output for the python --version is Python 3.5.2
Still getting the following:

```
Using TensorFlow backend.
> Loading data...
> Data Loaded. Compiling...
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    model = lstm.build_model([1, 50, 100, 1])
  File "/root/LSTM/lstm.py", line 53, in build_model
    return_sequences=True))
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/recurrent.py", line 931, in __init__
    super(LSTM, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/recurrent.py", line 181, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 275, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_dim')
```

**Comment by jaungiers** [comment]
Well then it looks like Keras is failing on something. All I can think of is that you're using a version of Keras that isn't the same as mine. Make sure you're using Keras 1.2.2 or if you want to use a different version then check the docs for your version's namespace arguments

**Comment by BasharAG** [comment]
Keras was the problem. I uninstalled it, then tried to run the application but got an error that module keras wasn't found. I installed it again using pip3, and now it works :) Thanks alot! 👍

**Comment by shaktisd** [comment]
Change line number 51 in lstm.py to make it work in keras 2.0
from input_dim=layers[0],
to input_shape=(layers[1], layers[0]),
