### ISSUE TITLE
KeyError: 'save_dir'

### ISSUE THREAD

**Issue by ghost** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#79]
PS C:\Users\iketu\Documents\Machine Learning Notebooks\LSTM Time Series Prediction> python run.py
2020-07-24 11:03:32.566952: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; 
dlerror: cudart64_101.dll not found
2020-07-24 11:03:32.567274: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "run.py", line 86, in <module>
    main()
  File "run.py", line 33, in main
    if not os.path.exists(configs['model']['save_dir']): os.makedirs(configs['model']['save_dir'])
KeyError: 'save_dir'

![Screenshot (4)](https://user-images.githubusercontent.com/22612178/88363554-117aaa80-cd9e-11ea-9d00-becac9e3d41d.png)

**Comment by VincieD** [comment]
Hi, you simply dont have the "save_dir" in your config.json. Or you have in not in the "model" attribute.
